//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent_Hunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string status { get; set; }
    }
}
