//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent_Hunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int Id { get; set; }
        public Nullable<int> SubmissionID { get; set; }
        public Nullable<int> CommitteeMemberID { get; set; }
        public Nullable<int> Marks1 { get; set; }
    }
}
